name = "ai-search"
main = "src/worker/index.js"
compatibility_date = "2024-01-01"

# AI 绑定配置
[ai]
binding = "AI"

# Pages 配置
pages_build_output_dir = "pages"

# 自定义子域名配置
# Worker API: https://ai-search.tsaitang.workers.dev
# Pages前端: https://search.tsaitang.workers.dev

# 您可以在这里添加自定义域名
# routes = [
#   { pattern = "search.tsaitang.workers.dev/*", zone_name = "tsaitang.workers.dev" }
# ]

# 环境变量配置
# [vars]
# 使用AI绑定，不需要额外的环境变量

# 开发环境配置
[dev]
port = 8787

# 您可以在这里配置KV、D1数据库或其他Cloudflare资源
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
