name = "search-frontend"
main = "src/frontend/index.js"
compatibility_date = "2024-01-01"

# 自定义域名配置
# 注意：您需要确保tsaitang.workers.dev域名在您的Cloudflare账户中可用
# routes = [
#   { pattern = "search.tsaitang.workers.dev/*", zone_name = "tsaitang.workers.dev" }
# ]

# 部署后将使用: https://search-frontend.tsaitang.workers.dev
# 可以通过Cloudflare Dashboard配置自定义域名为: search.tsaitang.workers.dev
