name = "neoai"
main = "../src/worker/index.js"
compatibility_date = "2024-01-01"

# AI 绑定配置
[ai]
binding = "AI"

# D1 数据库绑定配置
[[d1_databases]]
binding = "DB"
database_name = "neoai"
database_id = "11a6a452-a8b6-4d10-9963-f5a204bd02d0"

# 开发环境配置
[dev]
port = 8787

# 自定义域名配置 (可选)
# 您可以通过Cloudflare Dashboard配置自定义域名
# 例如: search.yourdomain.com → neoai

# 您可以在这里配置KV、D1数据库或其他Cloudflare资源
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
